# Generated by Django 4.2.7 on 2023-12-25 19:15

from django.db import migrations, models
import fileshare.models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0002_file_remove_folder_name_folder_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=fileshare.models.get_upload_data),
        ),
    ]
